version: '3'

services:
  app:
    image: geo
    volumes:
      - .:/backend
    depends_on:
      - geospatial
    ports:
      - "8000:8000"

  geospatial:
    image: kartoza/postgis
    container_name: geospatial
    environment:
      - POSTGRES_PASS=123456789
      - POSTGRES_USER=user001
      - POSTGRES_DBNAME=gis
    ports:
      - "5432:5432"
    volumes:
      - geospatial_volume:/var/lib/postgresql/data
volumes:
  geospatial_volume:
